### ISSUE TITLE
Provide formatting options to messages printed in prescriptions

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1971]
**Is your feature request related to a problem? Please describe.**

As a Thoth maintainer, I would like to create generic prescriptions which messages can be formatted using predefined set of values to expand. An example can be a prescription that notifies about package installation from an index and the message should print such a fact:

```yaml
name: PulpMessageWrap
type: wrap
should_include:
match:
  state:
    resolved_dependencies:
      - index_url: "https://pulp.operate-first.cloud/pypi/fpokorny-test/"
run:
  justification:
    - type: INFO
      message: "Package {package_name!r} in version {package_version!r} is installed from {index_url!r}"
      link: "{index_url}"
```

**Describe the solution you'd like**

Provide an interface for parametrizing prescription messages.

**Acceptance Criteria**
- [ ] documentation page on t-s.ninja listing all variables available for templates
