### ISSUE TITLE
Support library usage globing in prescriptions

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2008]
**Is your feature request related to a problem? Please describe.**

As Thoth administrator and user, I would like to create prescriptions that state library usage in a globbed form:

```yaml
  library_usage:
    tensorflow:
      - tensorflow.keras.*
```

This way I can specify pipeline units that should be activated during the resolution process when anything from tensorflow.keras is imported.
