### ISSUE TITLE
Allow matching only one package from multiple in prescriptions

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2098]
**Is your feature request related to a problem? Please describe.**

As a user of the recommender system, I would like to make sure that each prescription that is matched is run only once even though multiple packages are stated:

```yaml
match:
- resolved_dependencies:
   name: flask
- resolved_dependencies:
   name: connexion
```

This way we can make sure the logic behind the prescription is run once. This can be suitable for cases such as https://github.com/thoth-station/prescriptions/pull/17213/files
