### ISSUE TITLE
Use higher level abstraction for CPU features

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2114]
**Is your feature request related to a problem? Please describe.**

As discussed on the Tech talk:

I, as a user of Thoth, would like to configure prescriptions based on features CPU provide, example:

```yaml
units:
  sieves:
  - name: DeepSparseAVX512Sieve
    type: sieve
    should_include:
      adviser_pipeline: true
      runtime_environments:
        hardware:
        -  cpu_features: [“avx2”, “avx512” ]
```

This way, the prescription can be included based on hardware features available and the underlying logic can map the features to the corresponding cpu models and cpu families under the hood (based on database).

**Describe alternatives you've considered**

Keep "`cpu_family`" and "`cpu_model`" but that looks too low level for many cases.

**Additional context**

References: https://docs.google.com/document/d/1XmXYEWEwgOBHqdJkUTmhBvUb41pr5GIR2pePasvvZ1s/edit#
References: https://github.com/thoth-station/prescriptions/pull/18515
