### ISSUE TITLE
Provide a way to additionally specify tags on the container images in prescriptions

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2117]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth's adviser and prescriptions, I would like to have the power to express that any tag of a container image is acceptable for a prescription so that it can be included. 

Example:

```yaml
units:
  sieves:
  - name: FooSieve
    type: sieve
    should_include:
      adviser_pipeline: true
      runtime_environments:
        base_images:
        -  quay.io/thoth-station/s2i-thoth-ubi8-py38:*  # << Any S2I Thoth on UBI8 Python 3.8
        -  quay.io/thoth-station/s2i-thoth-ubi8-py36:v1.0.0
        -  quay.io/thoth-station/s2i-thoth-ubi8-py36:v1.1.0
```

**Describe the solution you'd like**

Create a logic that can state that "any" version of the container image is acceptable. We could also follow other parts of the prescriptions and use regular expressions to match the base image.
