### ISSUE TITLE
Add metadata field to justification schema

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/adviser#2166]
**Is your feature request related to a problem? Please describe.**
I am in the process of creating new justifications which will require storing json type data (string format). To keep the justification user readable, it can not go in the `message` param of the justification.

**Describe the solution you'd like**
I would like to add a metadata field in the justification yaml to hold any non user readable data. The justification remains readable (condensing raw data into some written result), while still holding the raw data that produced that result.
```
units:
  wraps:
   - name: FooWrap
     type: wrap
     metadata:
       key: 
         subKey:
            subsubkey: value
      ...
```

**Describe alternatives you've considered**
I can store a stringified version of the data in the message field, but that is not user readable.
