### ISSUE TITLE
Provide a generic advise_manifest_changes in results that can be retrieved and used by thamos

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#2211]
It might be good to provide a generic mechanism for this `advised_manifest_changes` so we can generalize the feature. Something like (rough design just to show the functionality):

```yaml
advised_manifest_changes:
 - file: .thoth.yaml  # File that should be patched (can be also a buildconfig or so).
   patch:
     add: ...
```

_Originally posted by @fridex in https://github.com/thoth-station/thamos/issues/910#issuecomment-942307322_
