### ISSUE TITLE
Provide guidance when updating/downgrading versions

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2436]
## Problem statement

I, as a developer, would like to know any information when updating or downgrading a package. This information can involve info from a changelog or so. This could involve static source code analysis but also other parts.

## Proposal description

Add a new feature to prescriptions that would allow declaring what to report to users. A high level example:

```yaml
name: ExampleUnit
type: update.step
should_include:
  adviser_pipeline: true
match:
- package_version:
    name: flask
    version: "==2.1.0"
    index_url: https://pypi.org/simple
run:
  stack_info:
  - type: INFO
    message: safe_join is removed, use werkzeug.utils.safe_join instead
    link: https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-1-0
```
