### ISSUE TITLE
[Adviser exception] list index out of range for user_stack_scoring

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#897]
**Describe the bug**
The adviser run failed while  running `thamos advise`. 

**To Reproduce**
1. Pipfile: 
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
cowsay = ">=2.0.3"

[requires]
python_version = "3.6"
```
2. setup .thoth.yaml 
```
host: 'khemenu.thoth-station.ninja'
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: 'rhel:8.0'
    operating_system:
      name: 'rhel'
      version: '8.0'
    python_version: '3.6'
    recommendation_type: STABLE

managers:
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
  - name: thoth-provenance
    configuration:
      labels: [bot, kebechet]
```
3. Run advise with `thamos advise`

**Expected behavior**
Successful adviser run and some output.

**Additional context**
The adviser run which failed. logs: [cluster logs](https://paas.psi.redhat.com/console/project/thoth-prod-tensorflow/browse/pods/adviser-60956f2b-8zmfh?tab=logs)  Temporary 

Error part of the log: 
```
{
  "name": "thoth.adviser.run",
  "levelname": "ERROR",
  "module": "run",
  "lineno": 128,
  "funcname": "subprocess_run",
  "created": 1585717536.3975358,
  "asctime": "2020-04-01 05:05:36,397",
  "msecs": 397.5358009338379,
  "relative_created": 3574.676990509033,
  "process": 92,
  "message": "Adviser raised exception: list index out of range
              Traceback (most recent call last):
                File \"/opt/app-root/lib/python3.6/site-packages/thoth/adviser/run.py\", line 75, in subprocess_run
                  user_stack_scoring=user_stack_scoring
                File \"/opt/app-root/lib/python3.6/site-packages/thoth/adviser/resolver.py\", line 1126, in resolve
                  with_devel=with_devel, user_stack_scoring=user_stack_scoring
                File \"/opt/app-root/lib/python3.6/site-packages/thoth/adviser/resolver.py\", line 1077, in _do_resolve_products
                  self.beam.max().score,
                File \"/opt/app-root/lib/python3.6/site-packages/thoth/adviser/beam.py\", line 187, in max
                  self._max = (self._heapq[idx], idx)
              IndexError: list index out of range"
}
```
